<?php

return [
    'api_url' => env('WIKIMEDIA_COMMONS_API_URL', 'https://commons.wikimedia.org/w/api.php'),
    'user_agent' => env('WIKIMEDIA_USER_AGENT', 'RetroShirts/1.0 (portfolio project)'),
    'timeout' => (int) env('WIKIMEDIA_TIMEOUT', 20),
    'max_image_bytes' => (int) env('WIKIMEDIA_MAX_IMAGE_BYTES', 8_388_608),
    'default_price_cents' => (int) env('RETRO_CATALOG_PRICE_CENTS', 8495),

    'sizes' => [
        'S' => ['price_delta_cents' => 0, 'stock' => 5],
        'M' => ['price_delta_cents' => 0, 'stock' => 8],
        'L' => ['price_delta_cents' => 0, 'stock' => 7],
        'XL' => ['price_delta_cents' => 200, 'stock' => 4],
        'XXL' => ['price_delta_cents' => 400, 'stock' => 2],
    ],

    /*
    |--------------------------------------------------------------------------
    | Archivo retro curado
    |--------------------------------------------------------------------------
    |
    | Son plantillas históricas alojadas en Wikimedia Commons. El importador
    | consulta la API oficial, conserva autor/licencia y descarga la imagen.
    | No son fotografías del artículo físico que se vende.
    |
    */
    'shirts' => [
        ['team' => 'afc-ajax', 'season' => '1994-95', 'type' => 'home', 'file' => 'Kit body ajax94h.png'],
        ['team' => 'afc-ajax', 'season' => '1994-95', 'type' => 'away', 'file' => 'Kit body ajax9495a.png'],
        ['team' => 'afc-ajax', 'season' => '1995-96', 'type' => 'home', 'file' => 'Kit body ajax96.png'],
        ['team' => 'afc-ajax', 'season' => '2000-01', 'type' => 'away', 'file' => 'Kit body ajax0001a.png'],
        ['team' => 'afc-ajax', 'season' => '2001-02', 'type' => 'home', 'file' => 'Kit body ajax0102h.png'],
        ['team' => 'real-madrid-cf', 'season' => '1980-81', 'type' => 'away', 'file' => 'Kit body RM1980A.png'],
        ['team' => 'real-madrid-cf', 'season' => '1990-91', 'type' => 'home', 'file' => 'Kit body rmcf9091h.png'],
        ['team' => 'real-madrid-cf', 'season' => '1990-91', 'type' => 'away', 'file' => 'Kit body rmcf9091a.png'],
        ['team' => 'real-madrid-cf', 'season' => '1990-91', 'type' => 'goalkeeper', 'file' => 'Kit body rmcf9091g1.png'],
        ['team' => 'real-madrid-cf', 'season' => '1992-93', 'type' => 'away', 'file' => 'Kit body rmcf9293a.png'],
        ['team' => 'real-madrid-cf', 'season' => '1993-94', 'type' => 'home', 'file' => 'Kit body rmcf9394.png'],
        ['team' => 'real-madrid-cf', 'season' => '1993-94', 'type' => 'away', 'file' => 'Kit body rmcf9394a.png'],
        ['team' => 'real-madrid-cf', 'season' => '1996-97', 'type' => 'away', 'file' => 'Kit body rmcf9697a.png'],
        ['team' => 'real-madrid-cf', 'season' => '1997-98', 'type' => 'third', 'file' => 'Kit body rmcf9798t.png'],
        ['team' => 'real-madrid-cf', 'season' => '1998-99', 'type' => 'home', 'file' => 'Kit body real9899h.png'],
        ['team' => 'real-madrid-cf', 'season' => '1998-99', 'type' => 'away', 'file' => 'Kit body rmcf9899a.png'],
        ['team' => 'fc-barcelona', 'season' => '1991-92', 'type' => 'home', 'file' => 'Kit body fcb 1992 cl final.png'],
        ['team' => 'fc-barcelona', 'season' => '1997-98', 'type' => 'home', 'file' => 'Kit body barcelona98.png'],
        ['team' => 'fc-barcelona', 'season' => '1997-98', 'type' => 'away', 'file' => 'Kit body barcelona98a.png'],
        ['team' => 'fc-barcelona', 'season' => '1998-99', 'type' => 'home', 'file' => 'Kit body barcelona99h.png'],
        ['team' => 'fc-barcelona', 'season' => '1998-99', 'type' => 'away', 'file' => 'Kit body barcelona99a.png'],
        ['team' => 'juventus-fc', 'season' => '1979-80', 'type' => 'away', 'file' => 'Kit body juve7980a.png'],
        ['team' => 'juventus-fc', 'season' => '1980-81', 'type' => 'home', 'file' => 'Kit body juve198081h.png'],
        ['team' => 'juventus-fc', 'season' => '1990-91', 'type' => 'home', 'file' => 'Kit body juve199091h.png'],
        ['team' => 'juventus-fc', 'season' => '1990-91', 'type' => 'third', 'file' => 'Kit body juve9091t2.png'],
        ['team' => 'juventus-fc', 'season' => '1995-96', 'type' => 'home', 'file' => 'Kit body juve9596h.png'],
        ['team' => 'juventus-fc', 'season' => '1995-96', 'type' => 'away', 'file' => 'Kit body juventus9596a.png'],
        ['team' => 'juventus-fc', 'season' => '1995-96', 'type' => 'third', 'file' => 'Kit body juve9596t.png'],
        ['team' => 'ac-milan', 'season' => '1988-89', 'type' => 'home', 'file' => 'Kit body milan8889h.png'],
        ['team' => 'ac-milan', 'season' => '1988-89', 'type' => 'away', 'file' => 'Kit body milan8889a.png'],
        ['team' => 'ac-milan', 'season' => '1989-90', 'type' => 'home', 'file' => 'Kit body acmilan8990h.png'],
        ['team' => 'ac-milan', 'season' => '1989-90', 'type' => 'goalkeeper', 'file' => 'Kit body milan90gk.png'],
        ['team' => 'ac-milan', 'season' => '2000-01', 'type' => 'third', 'file' => 'Kit body acm0001t.png'],
        ['team' => 'ac-milan', 'season' => '2000-02', 'type' => 'away', 'file' => 'Kit body acm0002a.png'],
        ['team' => 'manchester-united', 'season' => '1988-92', 'type' => 'away', 'file' => 'Kit body manutda8892.png'],
        ['team' => 'manchester-united', 'season' => '1992-94', 'type' => 'home', 'file' => 'Kit body manutd9293h.png'],
        ['team' => 'manchester-united', 'season' => '1992-93', 'type' => 'away', 'file' => 'Kit body manutd9293a.png'],
        ['team' => 'manchester-united', 'season' => '1993-94', 'type' => 'away', 'file' => 'Kit body manutd9394a.png'],
        ['team' => 'manchester-united', 'season' => '1994-96', 'type' => 'home', 'file' => 'Kit body manutd9495h.png'],
        ['team' => 'manchester-united', 'season' => '1994-96', 'type' => 'third', 'file' => 'Kit body manutd39496.png'],
        ['team' => 'manchester-united', 'season' => '1996-98', 'type' => 'home', 'file' => 'Kit body manutd9697h.png'],
        ['team' => 'manchester-united', 'season' => '1996-98', 'type' => 'third', 'file' => 'Kit body manutd39698.png'],
        ['team' => 'manchester-united', 'season' => '1998-99', 'type' => 'home', 'file' => 'Kit body manutd9899h.png'],
        ['team' => 'manchester-united', 'season' => '1998-99', 'type' => 'third', 'file' => 'Kit body manutd9899t.png'],
        ['team' => 'manchester-united', 'season' => '2000-01', 'type' => 'third', 'file' => 'Kit body manutd0001t.png'],
        ['team' => 'liverpool-fc', 'season' => '1983-84', 'type' => 'home', 'file' => 'Kit body liverpool84.png'],
        ['team' => 'liverpool-fc', 'season' => '1985-88', 'type' => 'goalkeeper', 'file' => 'Kit body liverpool8588g2.png'],
        ['team' => 'liverpool-fc', 'season' => '1987-89', 'type' => 'home', 'file' => 'Kit body liverpool8789h.png'],
        ['team' => 'liverpool-fc', 'season' => '1989-91', 'type' => 'home', 'file' => 'Kit body liverpool8991h.png'],
        ['team' => 'liverpool-fc', 'season' => '1993-95', 'type' => 'home', 'file' => 'Kit body liverpool9395h.png'],
        ['team' => 'liverpool-fc', 'season' => '1995-96', 'type' => 'away', 'file' => 'Kit body liverpool9596a.png'],
        ['team' => 'liverpool-fc', 'season' => '1999-2000', 'type' => 'away', 'file' => 'Kit body liverpool9900a.png'],
        ['team' => 'liverpool-fc', 'season' => '2001-02', 'type' => 'away', 'file' => 'Kit body liverpool0102a.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1981-82', 'type' => 'goalkeeper', 'file' => 'Kit body bayern8182g1.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1982-83', 'type' => 'goalkeeper', 'file' => 'Kit body bayern8283g1.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1996-98', 'type' => 'goalkeeper', 'file' => 'Kit body bayern9697g1.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1997-98', 'type' => 'home', 'file' => 'Kit body Bayern9798h.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1997-98', 'type' => 'third', 'file' => 'Kit body Bayern9798t.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1997-98', 'type' => 'goalkeeper', 'file' => 'Kit body bayern9798g2.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1998-99', 'type' => 'home', 'file' => 'Kit body bayern9899.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1998-00', 'type' => 'away', 'file' => 'Kit body Bayern9800a.png'],
        ['team' => 'fc-bayern-munchen', 'season' => '1998-00', 'type' => 'third', 'file' => 'Kit body Bayern9800t.png'],
        ['team' => 'fc-porto', 'season' => '1984-85', 'type' => 'home', 'file' => 'Kit body porto198485h.png'],
        ['team' => 'fc-porto', 'season' => '2003-04', 'type' => 'home', 'file' => 'Kit body porto0304h.png'],
        ['team' => 'fc-porto', 'season' => '2003-04', 'type' => 'away', 'file' => 'Kit body porto0304a.png'],
        ['team' => 'celtic-fc', 'season' => '1987-89', 'type' => 'home', 'file' => 'Kit body celtic8789h.png'],
        ['team' => 'boca-juniors', 'season' => '1986-88', 'type' => 'away', 'file' => 'Kit body boca8688a.png'],
        ['team' => 'boca-juniors', 'season' => '1988-92', 'type' => 'away', 'file' => 'Kit body boca8892a.png'],
        ['team' => 'clube-de-regatas-do-flamengo', 'season' => '1980', 'type' => 'home', 'file' => 'Kit body flamengo80h.png'],
        ['team' => 'clube-de-regatas-do-flamengo', 'season' => '1984', 'type' => 'home', 'file' => 'Kit body flamengo84h.png'],
        ['team' => 'clube-de-regatas-do-flamengo', 'season' => '1987', 'type' => 'home', 'file' => 'Kit body flamengo87h.png'],
        ['team' => 'clube-de-regatas-do-flamengo', 'season' => '1993-95', 'type' => 'home', 'file' => 'Kit body fla93h.png'],
        ['team' => 'clube-de-regatas-do-flamengo', 'season' => '1993-95', 'type' => 'away', 'file' => 'Kit body fla93a.png'],
        ['team' => 'sociedade-esportiva-palmeiras', 'season' => '1993', 'type' => 'home', 'file' => 'Kit body sep93.png'],
        ['team' => 'seleccion-de-italia', 'season' => '1982-90', 'type' => 'home', 'file' => 'Kit body italy1982-90.png'],
        ['team' => 'seleccion-de-italia', 'season' => '1986-90', 'type' => 'home', 'file' => 'Kit body ita90.png'],
        ['team' => 'seleccion-de-italia', 'season' => '1994', 'type' => 'home', 'file' => 'Kit body ita94h1.png'],
        ['team' => 'seleccion-de-italia', 'season' => '1996', 'type' => 'home', 'file' => 'Kit body ita96.png'],
        ['team' => 'seleccion-de-alemania', 'season' => '1980', 'type' => 'home', 'file' => 'Kit body westgermany1980.png'],
        ['team' => 'seleccion-de-alemania', 'season' => '1988-90', 'type' => 'home', 'file' => 'Kit body ger88h.png'],
        ['team' => 'seleccion-de-alemania', 'season' => '1990', 'type' => 'home', 'file' => 'Kit body ger90h.png'],
        ['team' => 'seleccion-de-alemania', 'season' => '1992', 'type' => 'home', 'file' => 'Kit body ger92h.png'],
        ['team' => 'seleccion-de-alemania', 'season' => '1992', 'type' => 'away', 'file' => 'Kit body ger92a.png'],
        ['team' => 'seleccion-de-alemania', 'season' => '1996', 'type' => 'home', 'file' => 'Kit body DFB 96h.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1980', 'type' => 'away', 'file' => 'Kit body netherlands80a.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1988', 'type' => 'home', 'file' => 'Kit body netherlands1988.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1990', 'type' => 'home', 'file' => 'Kit body netherlands90h.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1990', 'type' => 'away', 'file' => 'Kit body netherlands90a.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1990', 'type' => 'goalkeeper', 'file' => 'Kit body ned90g2.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1996', 'type' => 'home', 'file' => 'Kit body netherlands96h.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1996', 'type' => 'goalkeeper', 'file' => 'Kit body ned96g1.png'],
        ['team' => 'seleccion-de-paises-bajos', 'season' => '1998-2000', 'type' => 'away', 'file' => 'Kit body nether00a.png'],
        ['team' => 'seleccion-de-dinamarca', 'season' => '1984', 'type' => 'home', 'file' => 'Kit body denmark84.png'],
        ['team' => 'seleccion-de-dinamarca', 'season' => '1992', 'type' => 'home', 'file' => 'Kit body denmark1992.png'],
        ['team' => 'seleccion-de-dinamarca', 'season' => '2000', 'type' => 'away', 'file' => 'Kit body den00A.png'],
        ['team' => 'seleccion-de-brasil', 'season' => '1990', 'type' => 'home', 'file' => 'Kit body bra90h1.png'],
        ['team' => 'seleccion-de-brasil', 'season' => '1990', 'type' => 'away', 'file' => 'Kit body bra90a1.png'],
        ['team' => 'seleccion-de-brasil', 'season' => '1994', 'type' => 'home', 'file' => 'Kit body brazil1994.png'],
        ['team' => 'seleccion-de-brasil', 'season' => '1994', 'type' => 'goalkeeper', 'file' => 'Kit body brazil94gk1.png'],
        ['team' => 'seleccion-de-brasil', 'season' => '1996', 'type' => 'away', 'file' => 'Kit body bra96a.png'],
        ['team' => 'seleccion-de-argentina', 'season' => '1986', 'type' => 'home', 'file' => 'Kit body argentina1986.png'],
        ['team' => 'seleccion-de-argentina', 'season' => '1990', 'type' => 'away', 'file' => 'Kit body argentina1990a.png'],
        ['team' => 'seleccion-de-argentina', 'season' => '1990', 'type' => 'goalkeeper', 'file' => 'Kit body argentina1990gk1.png'],
        ['team' => 'seleccion-de-argentina', 'season' => '1992', 'type' => 'home', 'file' => 'Kit body argentina1992.png'],
        ['team' => 'seleccion-de-mexico', 'season' => '1980', 'type' => 'home', 'file' => 'Kit body mex80h.png'],
        ['team' => 'seleccion-de-mexico', 'season' => '1996', 'type' => 'home', 'file' => 'Kit body mex96oh.png'],
        ['team' => 'seleccion-de-mexico', 'season' => '1998', 'type' => 'home', 'file' => 'Kit body mex98.png'],
        ['team' => 'seleccion-de-nigeria', 'season' => '1994', 'type' => 'home', 'file' => 'Kit body nga94h1.png'],
        ['team' => 'seleccion-de-nigeria', 'season' => '1994', 'type' => 'away', 'file' => 'Kit body nga94a1.png'],
        ['team' => 'seleccion-de-nigeria', 'season' => '1994', 'type' => 'goalkeeper', 'file' => 'Kit body nga94gkh.png'],
        ['team' => 'seleccion-de-camerun', 'season' => '1990', 'type' => 'home', 'file' => 'Kit body cameroon1990 home.png'],
        ['team' => 'seleccion-de-camerun', 'season' => '1990', 'type' => 'away', 'file' => 'Kit body cameroon1990 away.png'],
        ['team' => 'seleccion-de-camerun', 'season' => '1990', 'type' => 'goalkeeper', 'file' => 'Kit body cam90gk2.png'],
        ['team' => 'seleccion-de-croacia', 'season' => '1998', 'type' => 'home', 'file' => 'Kit body cro98h.png'],
        ['team' => 'seleccion-de-marruecos', 'season' => '1998', 'type' => 'home', 'file' => 'Kit body mor98.png'],
        ['team' => 'seleccion-de-marruecos', 'season' => '1998', 'type' => 'away', 'file' => 'Kit body mor98 away.png'],
    ],
];
